---
title : "Compte-rendu du **30/01/2020**"
# output: 
#   pdf_document
---

> Présent(e)s :  
>  - Aurélie Garcia (AG)  
>  - Léa Brieau (LB)  
>  - Régis Gallon (RG)

*LB* a été intégrée dans la mailing-list du projet OBADE

### **1. Description des variables et homogénéisation des libellés**

- Il faudrait une description plus précise des variables : `type de suivie`, `type de protocole`, `version protocole`
- Pour une même variable, il peut y avoir des noms différents : `Libellé Sortie`= `libellé sortie`

### **2. Le type de données à exploiter** 

- *Brouillon* : La fiche est incomplète
- *Terminé* : La fiche est terminée par l'opérateur
- *Validé* : La fiche est validée par un référent local (structure) ou national

*RG :* Pour la description des données j'utilise les données validées.
*AG :* Il faut vérifier les recommandations d'analyse des données (fichier envoyé par *LB*)

### **3. Mise en place du Comité de pilotage COPIL**
#### *3.1 Participants*

- **DIRMM** Juliette AMAT - juliette.amat@@developpement-durable.gouv.fr
- **DREAL** Normandie vérif avec Sandrine ROBBES ou convention
- **OFB** Sebastien BITON - sebastien.biton@@ofb.gouv.fr
- **AESN** Yann JONCOURT
- **AEAP** Jean PRIGEL - j.prygiel@@eau-artois-picardie.fr
- **AELB** Philippe FERAT 
- **URCPIE** Léa BRIEAU - observatoirepapl@@urcpie-normandie.com
- **OFB ESTAMP** Elodie GAMP - elodie.gamp@@ofb.gouv.fr
- **OFB ESTAMP** Guilhem AUTRET - guilhem.autret@@afbiodiversite.fr
- **Réseau Littorea** Franck DELISLE et Sarah OLIVIER - reseau.littorea@@gmail.com 
- **DDTM Manche** Remplaçant Célia D'Hervé
- **DDTM Calvados** ?
- **DDTM Côtes d'Armor** Valérie JAOUEN


#### *3.2 Organisation*

- Présentation du projet OBADE
- Description de la base
- Présentation des outils existants
- Quelles questions à répondre pour OBADE sur **les données d'usage**

### **4. Divers**

*RG :* Pour le COPIL création d'un modèle de document d'analyse selon le fichier (.xlsx) développé par *LB*. (*e.g.* Côtes d'Armor tous sites confondus) 

Conformité des paniers: Difficile à analyser car données qui n'ont pas les mêmes unités (poids, volume, nombre d'individus)

Voir l'intégration de la base SIG dans le site du projet OBADE [lien](https://lizmap.afbiodiversite.fr/aamp/afb_mer/index.php/view/map/?repository=bdestampbasesig&project=ref_met_bdestamp_ref_geo_pol)
